### ISSUE TITLE
请问，如果是多个库config里的库编号怎么写？

### ISSUE THREAD

**Issue by dskblh** [WadeChenn/Plex-Tools#10]
运行报这个错，是config哪里设置错了吗？目前是使用了库编号，填的值是all，命令行手动输入单个库编号可以运行，但是config内设置为all则报此错误

int() argument must be a string, a bytes-like object or a number, not 'builtin_function_or_method'
出错!
Traceback (most recent call last):
  File "/config/script/Plex-SortTittle.py", line 272, in <module>
    videos = plex.library.sectionByID(int(LIB_NUMBER))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'builtin_function_or_method'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/script/Plex-SortTittle.py", line 278, in <module>
    os._exit()
TypeError: _exit() missing required argument 'status' (pos 1)

**Comment by WadeChenn** [comment]
> 

use init 设置为true了吗

**Comment by dskblh** [comment]
是的，发现设置错了，all应该写在库名里，我之前写在库编号里了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年10月19日 13:24 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [WadeChenn/Plex-Tools] 请问，如果是多个库config里的库编号怎么写？ (Issue #10) |

use init 设置为true了吗
