### ISSUE TITLE
个别没有汉化

### ISSUE THREAD

**Issue by Ignatius-Ye** [WadeChenn/Plex-Tools#3]
![Screenshot_20220810_185632](https://user-images.githubusercontent.com/37823715/183886261-87b8f623-bb39-4113-87d7-eeebb7d1ca79.jpg)
![Screenshot_20220810_185134](https://user-images.githubusercontent.com/37823715/183886313-b3410f94-bfc9-4bab-9ff7-02240c338dd8.jpg)
Short/ Game Show / Travel 没有汉化

**Comment by WadeChenn** [comment]
已添加
"Short" :"短剧",
"Game Show":"游戏节目",
"Travel":"旅行",
