### ISSUE TITLE
代码框和下边截图不一样

### ISSUE THREAD

**Issue by xulin530** [WadeChenn/Plex-Tools#9]
大佬你好，Plex-SortTittle的Arguments tab页在 Recently Added 中填入下方代码的代码是"-mid 1"和下方截图不一样，我记得之前是和截图一样的，是新版本改了代码吗？

**Comment by WadeChenn** [comment]
> 大佬你好，Plex-SortTittle的Arguments tab页在 Recently Added 中填入下方代码的代码是"-mid 1"和下方截图不一样，我记得之前是和截图一样的，是新版本改了代码吗？

改了
